CREATE DATABASE UNICORN_INFO;
USE UNICORN_INFO;
CREATE TABLE SALES (
    SALE_ID INT NOT NULL,
    CUSTOMER_NAME VARCHAR(50),
    REGION VARCHAR(30),
    PRODUCT_NAME VARCHAR(50),
    QUANTITY INT DEFAULT 0,
    PRICE_PER_UNIT DECIMAL(10,2),
    SALE_DATE DATE
);
INSERT INTO SALES (SALE_ID, CUSTOMER_NAME, REGION, PRODUCT_NAME, QUANTITY, PRICE_PER_UNIT, SALE_DATE) VALUES
(1, 'NOAH SMITH', 'NORTH', 'LAPTOP', 2, 55000.00, '2025-01-15'),
(2, 'EMMA JOHNSON', 'EAST', 'HEADPHONES', 3, 2500.00, '2025-01-20'),
(3, 'LIAM BROWN', 'SOUTH', 'SMARTPHONE', 1, 30000.00, '2025-02-05'),
(4, 'OLIVIA DAVIS', 'WEST', 'TABLET', 2, 18000.00, '2025-02-12'),
(5, 'MASON WILSON', 'NORTH', 'MONITOR', 1, 12000.00, '2025-03-01'),
(6, 'AVA MILLER', 'EAST', 'KEYBOARD', 4, 1500.00, '2025-03-10'),
(7, 'LUCAS MOORE', 'SOUTH', 'MOUSE', 5, 800.00, '2025-03-18'),
(8, 'SOPHIA TAYLOR', 'WEST', 'PRINTER', 1, 9500.00, '2025-04-02'),
(9, 'ETHAN ANDERSON', 'NORTH', 'DESKTOP', 1, 40000.00, '2025-04-14'),
(10, 'ISABELLA THOMAS', 'EAST', 'SCANNER', 2, 7000.00, '2025-04-21'),
(11, 'JAMES JACKSON', 'SOUTH', 'LAPTOP', 1, 60000.00, '2025-05-09'),
(12, 'MIA WHITE', 'WEST', 'HEADPHONES', 3, 2800.00, '2025-05-18'),
(13, 'BENJAMIN HARRIS', 'NORTH', 'MONITOR', 2, 13000.00, '2025-06-05'),
(14, 'EVELYN MARTIN', 'EAST', 'TABLET', 1, 20000.00, '2025-06-15'),
(15, 'HENRY LEE', 'SOUTH', 'SMARTWATCH', 2, 8500.00, '2025-06-30');
ALTER TABLE SALES RENAME TO UNICORN_SALES;
SELECT SUM(QUANTITY) FROM UNICORN_SALES;
SELECT avg(PRICE_PER_UNIT) FROM UNICORN_SALES;
SELECT QUANTITY*PRICE_PER_UNIT FROM UNICORN_SALES AS NET_SALES;
SELECT REGION, COUNT(SALE_ID) AS TOTAL_SALES FROM UNICORN_SALES GROUP BY REGION;
SELECT CUSTOMER_NAME, COUNT(QUANTITY) AS PRODUCT_PER_CUST FROM UNICORN_SALES GROUP BY CUSTOMER_NAME;
SELECT REGION FROM UNICORN_SALES WHERE PRICE_PER_UNIT>= 50000;
SELECT AVG(QUANTITY) FROM UNICORN_SALES WHERE PRODUCT_NAME = 'LAPTOP';
CREATE TABLE CUSTOMER_INFO (
CUST_NAME TEXT(9),
CUST_REGION TEXT(9),
CUST_EMAIL VARCHAR (50)
);
INSERT INTO CUSTOMER_INFO (CUST_NAME, CUST_REGION, CUST_EMAIL) VALUES
('NOAH SMITH', 'NORTH', 'noah@example.com'),
('EMMA JOHNSON', 'EAST', 'emma@example.com'),
('LIAM BROWN', 'SOUTH', 'liam@example.com'),
('OLIVIA DAVIS', 'WEST', 'olivia@example.com'),
('MASON WILSON', 'NORTH', 'mason@example.com'),
('AVA MILLER', 'EAST', 'ava@example.com'),
('LUCAS MOORE', 'SOUTH', 'lucas@example.com'),
('SOPHIA TAYLOR', 'WEST', 'sophia@example.com'),
('ETHAN ANDERSON', 'NORTH', 'ethan@example.com'),
('ISABELLA THOMAS', 'EAST', 'isabella@example.com'),
('JAMES JACKSON', 'SOUTH', 'james@example.com'),
('MIA WHITE', 'WEST', 'mia@example.com'),
('BENJAMIN HARRIS', 'NORTH', 'benjamin@example.com'),
('EVELYN MARTIN', 'EAST', 'evelyn@example.com'),
('HENRY LEE', 'SOUTH', 'henry@example.com');

SELECT * FROM UNICORN_SALES  INNER JOIN CUSTOMER_INFO ON UNICORN_SALES.CUSTOMER_NAME = CUSTOMER_INFO.CUST_NAME;
SELECT * FROM UNICORN_SALES left JOIN CUSTOMER_INFO ON UNICORN_SALES.CUSTOMER_NAME = CUSTOMER_INFO.CUST_NAME;
SELECT * FROM CUSTOMER_INFO;
SELECT * FROM UNICORN_SALES RIGHT JOIN CUSTOMER_INFO ON UNICORN_SALES.CUSTOMER_NAME = CUSTOMER_INFO.CUST_NAME;
SELECT * FROM UNICORN_SALES left JOIN CUSTOMER_INFO ON UNICORN_SALES.CUSTOMER_NAME = CUSTOMER_INFO.CUST_NAME
UNION 
SELECT * FROM UNICORN_SALES RIGHT JOIN CUSTOMER_INFO ON UNICORN_SALES.CUSTOMER_NAME = CUSTOMER_INFO.CUST_NAME;
DESCRIBE CUSTOMER_INFO;
DESCRIBE UNICORN_SALES;
SELECT REGION, SUM(QUANTITY) AS TOTAL_QUANTITY FROM UNICORN_SALES GROUP BY REGION HAVING SUM(QUANTITY) >= 6;
START TRANSACTION ;
SELECT * FROM UNICORN_SALES WHERE REGION = 'NORTH';
UPDATE UNICORN_SALES SET QUANTITY = QUANTITY+10 ;
COMMIT;
SELECT * FROM UNICORN_SALES;








